spring.application.name=weather-server

# Porta HTTP do Spring Boot (não usada diretamente, mas necessária para o contexto)
server.port=8081

# Porta onde o servidor gRPC vai escutar
grpc.server.port=9090